### PR TITLE
first question.

### PR DESCRIPTION
**Pull request by ObsidianMaximus**
Solved the first question.

But as it never asked which method to use, I went with the simplest that came to my mind at first.

Open to corrections!

Thank you.

### CODE REVIEW

**Comment by ObsidianMaximus** [comment]
Added another file to depict similar output using C

**Review by GuptaDiva — APPROVED** [review]

**Comment by ObsidianMaximus** [comment]
thanks! :)

**Review by GuptaDiva — COMMENTED** [review]
Good Job

**Comment by ObsidianMaximus** [comment]
> Good Job

thank you didi :)

**Pull request merged**
